[workspace]
authors = ["Bill Katz <billkatz@gmail.com>"]
channels = ["conda-forge"]
name = "presentation"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
nodejs = ">=25.8.2,<25.9"
